### ISSUE TITLE
Scan updates .pre-commit-config.yaml with duplicate hook arguments

### ISSUE THREAD

**Issue by stujfiter** [slalombuild/secureli#151]
If specifying arguments to pre-commit hooks in .secureli.yaml, the scan will always prompt the user with
```
The config version installed is dbb2391b7f9d8c3ea24b8827bb345649, but the latest is e9388d14d3b4364e1684f2f1ba281f92
Upgrade now? [Y/n]:
```

Responding with `Y` causes secureli to add the argument to pre-commit-config.yaml twice.

This happens even if the config has not changed.

Example .secureli.yaml file that allows larger files to be committed
```
pre_commit:
  repos:
    - hooks:
      - id: check-added-large-files
        additional_args: ['--maxkb=1000']
      url: https://github.com/pre-commit/pre-commit-hooks
```

.pre-commit-config.yaml before 1st scan
```
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - exclude: .xcscheme$
    id: detect-secrets
  repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
- hooks:
  - id: swiftlint
  repo: https://github.com/realm/SwiftLint
  rev: 0.52.2
```

.pre-commit-config.yaml after first scan (responding to prompt with `Y`
```
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - args:
    - --maxkb=1000
    - --maxkb=1000
    id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - exclude: .xcscheme$
    id: detect-secrets
  repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
- hooks:
  - id: swiftlint
  repo: https://github.com/realm/SwiftLint
  rev: 0.52.2
```
