### ISSUE TITLE
Add missing linters for Java

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#161]

**Comment by gabenegron** [comment]
I pulled down the latest and tested this... here is what gets installed into the .pre-commit-config.yaml file. Is it OK that the mirror be tied to a personal GitHub repo like this? @rgraue @calebtonn 

```
- hooks:
  - id: checkstyle-java
  repo: https://github.com/rgraue/pre-commit-mirror-checkstyle
  rev: v0.1.15
```
